apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: buildkit
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "REGISTRY_DOMAIN_PLACEHOLDER": {
          "auth": "AUTH_B64_PLACEHOLDER"
        }
      }
    }